name: W2I-machine-learning-bootcamp

channels:
  - pytorch
  - fastai
  - defaults

dependencies:
  - pandas=0.24.*
  - python=3.7.*
  - matplotlib=3.0.*
  - jupyterlab
  - scikit-learn=0.20.*
  - pyarrow=0.11.*
  - py-xgboost=0.80.*
  - pytorch
  - torchvision
  - fastai
  - pip:
    - kaggle==1.5.*
